[toolchain]
channel    = "stable"
components = ["rustfmt", "clippy", "llvm-tools"]

targets = [
    "x86_64-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
]
