#!/usr/bin/sh 

chown root:root /usr/bin/sandbox
chmod u+s /usr/bin/sandbox

chmod 644 /usr/share/bash-completion/completions/sandbox
chmod 644 /usr/share/zsh/site-functions/_sandbox
chmod 644 /usr/share/fish/vendor_completions.d/sandbox.fish

chmod 644 /usr/share/man/man1/sandbox.1.gz

