name: Audit

on:
    push:
        paths:
            - "**/Cargo.toml"
            - "**/Cargo.lock"
        branches: ["main"]
    pull_request:
        branches: ["main"]
        paths:
            - "**/Cargo.toml"
            - "**/Cargo.lock"

env:
    CARGO_TERM_COLOR: always

jobs:
    security-audit:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - uses: actions/checkout@v4
            - uses: rustsec/audit-check@v2.0.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
