name: Formatting

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    run-fmt:
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - uses: actions/checkout@v4

            - name: Fmt
              run: cargo fmt
