name: Spell check

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    run-spell-check:
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - uses: actions/checkout@v4
            - uses: streetsidesoftware/cspell-action@v6
